linters:
  # Enable all available linters.
  # Default: false
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - goconst
    - gocritic
    - godot
    - godox
    - goerr113
    - goheader
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl

linters-settings:
  wsl:
    strict-append: false
    enforce-err-cuddling: true

  gomnd:
    # Values always ignored: "1", "1.0", "0" and "0.0"
    # Default: []
    ignored-numbers:
      - '2'
      - '20'
      - '0644'

issues:
  exclude-rules:
    - path: main.go
      text: "exitAfterDefer"